changes:
  - version: 1
  - version: 2
    deletions:
      - charts.istio.addonComponents
    renamings:
      - env/charts: env/apps
      - env/apps/gatekeeper-operator.yaml: env/apps/gatekeeper.yaml
      - env/apps/nginx-ingress.yaml: env/apps/ingress-nginx.yaml
      - env/apps/prometheus-operator.yaml: env/apps/prometheus.yaml
    relocations:
      - charts: apps
      - apps.gatekeeper-operator: apps.gatekeeper
      - apps.nginx-ingress: apps.ingress-nginx
      - apps.prometheus-operator: apps.prometheus
      - apps.prometheus.grafana: apps.grafana
      - apps.prometheus.resources.grafana: apps.grafana.resources
      - apps.prometheus.alertmanager: apps.alertmanager
      - apps.prometheus.resources.alertmanager: apps.alertmanager.resources
