bases:
  - snippets/defaults.yaml
---
bases:
  - snippets/env.gotmpl
---
bases:
  - snippets/derived.gotmpl
---
{{ readFile "snippets/templates.gotmpl" }}
{{- $v := .Values }}
{{- $coreAdminServices := list }}
{{- range $s := $v.adminApps }}
{{- if $v.apps | get $s.name | get "enabled" false }}
{{- range $ing := $s | get "ingress" list }}
{{- $svc := merge $ing (dict "isCore" true "name" $s.name "isShared" ($s | get "isShared" false)) }}
{{- $coreAdminServices = append $coreAdminServices $svc }}
{{- end }}
{{- end }}
{{- end }}
{{- $c := $v.apps }}
{{- $cm := index $v.apps "cert-manager" }}

releases:
  - name: team-ns-admin
    installed: true
    namespace: team-admin
    chart: ../charts/team-ns
    labels:
      tag: teams
      ingress: "true"
      team: admin
    values:
      - name: admin
        teamId: admin
        charts: {{- $v.apps | toYaml | nindent 10 }}
        oidc: {{- $v | get "oidc" dict | toYaml | nindent 10 }}
        cluster: {{- $v.cluster | toYaml | nindent 10 }}
        otomi: {{- $v.otomi | toYaml | nindent 10 }}
        domain: {{ $v | get "cluster.domainSuffix" nil }}
        services: {{- $coreAdminServices | toYaml | nindent 10 }}
        resourceQuota: null
