bases:
  - snippets/defaults.yaml
---
bases:
  - snippets/env.gotmpl
---
bases:
  - snippets/derived.gotmpl
---
{{ readFile "snippets/templates.gotmpl" }}
{{- $v := .Values }}
{{- $a := $v.apps }}

releases:
  - name: gitea-artifacts
    installed: {{ and $v._derived.untrustedCA ($a | get "gitea.enabled")  }}
    namespace: gitea
    labels:
      pkg: gitea
    <<: *raw
  - name: kiali-operator-artifacts
    installed: {{ and ($a | get "kiali.enabled") $v._derived.untrustedCA }}
    namespace: kiali
    labels:
      pkg: kiali
    <<: *raw
  - name: knative-init
    installed: {{ $a | get "knative.enabled" }}
    namespace: default
    labels:
      init: true
      pkg: knative
    <<: *skeleton
  - name: loki-artifacts
    installed: {{ $a | get "loki.enabled" }}
    namespace: monitoring
    labels:
      pkg: loki
    <<: *raw
  - name: vault-operator
    installed: {{ $a | get "vault.enabled" }}
    disableValidationOnInstall: true
    namespace: vault
    labels:
      pkg: vault
    <<: *default
