bases:
  - snippets/env.gotmpl
---
{{ readFile "snippets/templates.gotmpl" }}
{{- $v := .Environment.Values }}
{{- $c := $v.charts }}

releases:
  - name: job-keycloak
    {{- if hasKey $v "oidc" }}
    installed: {{ $c | get "keycloak.enabled" true }}
    {{- else }}
    installed: false
    {{- end }}
    labels:
      pkg: keycloak
      group: jobs
    <<: *jobs

