bases:
  - snippets/defaults.yaml
---
bases:
  - snippets/env.gotmpl
---
bases:
  - snippets/derived.gotmpl
---
{{ readFile "snippets/templates.gotmpl" }}
{{- $v := .Values }}
{{- $c := $v.apps }}

releases:
  - name: aws-ebs-csi-driver
    installed: {{ $c | get "aws-ebs-csi-driver.enabled" }}
    namespace: kube-system
    labels:
      init: true
      pkg: csi
      provider: aws 
    <<: *default
  - name: gatekeeper
    installed: {{ $c | get "gatekeeper.enabled" }}
    namespace: default
    chart: ../charts/gatekeeper
    disableValidationOnInstall: true
    labels:
      pkg: gatekeeper
    values:
      - ../values/gatekeeper/gatekeeper.gotmpl
      - snippets/common.gotmpl
  - name: ingress-nginx
    installed: true
    namespace: ingress
    labels:
      tag: ingress
      stage: prep
    <<: *default
  - name: ingress-nginx-private
    installed: {{ $c | get "ingress-nginx.private.enabled" }}
    namespace: ingress
    labels:
      tag: ingress
    chart: ../charts/ingress-nginx
    values:
      - ../values/ingress-nginx/ingress-nginx.gotmpl
      - ../values/ingress-nginx/ingress-nginx-private.gotmpl
