bases:
  - snippets/defaults.yaml
---
bases:
  - snippets/env.gotmpl
---
bases:
  - snippets/derived.gotmpl
---
{{ readFile "snippets/templates.gotmpl" }}
{{- $v := .Values }}
{{- $a := $v.apps }}

releases:
  - name: grafana-dashboards
    installed: true
    namespace: grafana
    <<: *default
  - name: jaeger-operator
    installed: true
    namespace: jaeger-operator
    disableValidationOnInstall: true
    <<: *default
  - name: kiali-operator
    installed: true
    namespace: kiali-operator
    disableValidationOnInstall: true
    labels:
      pkg: kiali
    <<: *default
  - name: loki
    installed: true
    namespace: monitoring
    <<: *default
  - name: prometheus-blackbox-exporter
    installed: true 
    namespace: monitoring
    <<: *default
  - name: promtail
    installed: true
    namespace: monitoring
    <<: *default
  - name: prometheus-msteams
    installed: {{ $a | get "prometheus-msteams.enabled" }}
    namespace: monitoring
    <<: *default
