bases:
  - snippets/defaults.yaml
---
bases:
  - snippets/env.gotmpl
---
bases:
  - snippets/derived.gotmpl
---
{{ readFile "snippets/templates.gotmpl" }}
{{- $v := .Values }}
{{- $a := $v.apps }}

releases:
  - name: istio-operator-artifacts
    installed: true
    namespace: istio-operator
    labels:
      pkg: istio
    chart: ../charts/raw
    values:
      - ../values/istio-operator/istio-operator-raw.gotmpl
      - snippets/common.gotmpl
  - name: kubernetes-external-secrets
    installed: {{ $a | get "vault.enabled" }}
    namespace: vault
    labels:
      pkg: vault
    <<: *default

