{{- $v := .Values }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: team-ns-quota
  labels: {{- include "team-ns.chart-labels" . | nindent 4 }}
spec:
  hard:
    count/quota: "1"
    {{- toYaml $v.resourceQuota | nindent 4 }}